### PR TITLE
My feature/show item image from inventory

### PR DESCRIPTION
**Pull request by ortegamarcel**
settings
checkbox
mouse-hover
zoom-in

# Problem
Some of my players have quest items in their inventory with an relevant image. Unfortunately, there is no option for them to make it bigger.

# Changes
* On some item sheets there is a new "Zoomable"-checkbox. If checked, the players can click on the item image in their inventory to open it in a larger dialog.
* The dialog is resizeable and the image scales with the dialog width.
* On which item sheets the checkbox appears can be configured in the game settings. There is also the option, that only the GM can see it. (Players can still "zoom in".)
* You can also completely disable this by leaving the settings value empty
* By default it applies to "Valuable"-items and only the GM can decide, if an image is zoomable or not.
* Showing a visual indication that an item image is clickable/zoomable.
* Supports english and german

# Small other changes
* Fixed column headers of Valuables in Inventory
* Translated all (other) settings to german

### CODE REVIEW

**Comment by Melkkart** [comment]
Wonderful , one question, @ortegamarcel this version of the Zoomable objects, which by the way, I love, you do not have the improvements you did before, no? I don't know if I'm doing it right, but in this version I will see the zoomable option, but for example action.js has the armature error and I don't see your improvement, the one that organizes the objects. 
Could you create a version that has all the improvements you have made? 
I don't know if it's possible, but thanks!

**Comment by ortegamarcel** [comment]
> Wonderful , one question, @ortegamarcel this version of the Zoomable objects, which by the way, I love, you do not have the improvements you did before, no?
@Melkkart Thanks, but what improvements do you mean? The improved inventory? This is just the PR for my personal develop branch/repo. It does include all my previous changes, I just didn't change the screenshots.

> I don't know if I'm doing it right, but in this version I will see the zoomable option, but for example action.js has the armature error and I don't see your improvement, the one that organizes the objects.
What action.js error do you mean? And what does it have to do with this feature?

> Could you create a version that has all the improvements you have made? I don't know if it's possible, but thanks!
Sure, it is possible. But this already includes everything. Or do you mean on the other PR?

**Comment by Melkkart** [comment]
ok ok, nothing, don't mind me, it was my mistake, everything is fine, I've been testing and changing so much, I did something wrong. :) again thanks for everything and forgive me, I still have to learn a lot.

**Comment by ortegamarcel** [comment]
@Melkkart Don't worry. This happens to me often too.

**Pull request merged**
